### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TroniPM** [tiancaiamao/darkeden#1]
Hello buddy, do you have the client source code files? 
cliente: [opendarkeden/client](https://github.com/opendarkeden/client) hasn't any file
server: [opendarkeden/server](https://github.com/opendarkeden/server) has files

I want to play around with these files, but I need the client. Do you own or know where to find it?

**Comment by tiancaiamao** [comment]
No, it's removed.
I didn't backup it.

**Comment by TroniPM** [comment]
Do you know where i can find it?

**Comment by tiancaiamao** [comment]
You can visit here:
http://forum.ragezone.com/f857/darkeden-server-source-koffes-dk2-846480/

Many MMORPG source can be found, but maybe not darkeden.

**Comment by TroniPM** [comment]
Thanks.
